import type { Recipe } from '@/lib/recommendation';

export const recipeSeed: Recipe[] = [
  {
    id: 'spinach-paneer-bhurji',
    name: 'Spinach Paneer Bhurji',
    cuisine: 'North Indian',
    mealType: 'Dinner',
    prepTimeMin: 10,
    cookTimeMin: 15,
    ingredients: [
      { name: 'spinach', quantity: 200, unit: 'g' },
      { name: 'paneer', quantity: 150, unit: 'g' },
      { name: 'onion', quantity: 60, unit: 'g' },
      { name: 'tomato', quantity: 80, unit: 'g' },
      { name: 'garlic', quantity: 10, unit: 'g' },
      { name: 'greenchilli', quantity: 10, unit: 'g' },
    ],
    tags: ['vegetarian', 'high-protein'],
  },
  {
    id: 'moong-dal-tadka',
    name: 'Moong Dal Tadka',
    cuisine: 'Indian',
    mealType: 'Lunch',
    prepTimeMin: 10,
    cookTimeMin: 25,
    ingredients: [
      { name: 'moongdal', quantity: 180, unit: 'g' },
      { name: 'tomato', quantity: 120, unit: 'g' },
      { name: 'onion', quantity: 70, unit: 'g' },
      { name: 'garlic', quantity: 15, unit: 'g' },
      { name: 'ginger', quantity: 10, unit: 'g' },
      { name: 'spinach', quantity: 100, unit: 'g' },
    ],
    tags: ['vegetarian', 'protein'],
  },
  {
    id: 'veg-biryani',
    name: 'Vegetable Biryani',
    cuisine: 'Hyderabadi',
    mealType: 'Dinner',
    prepTimeMin: 20,
    cookTimeMin: 35,
    ingredients: [
      { name: 'rice', quantity: 250, unit: 'g' },
      { name: 'onion', quantity: 100, unit: 'g' },
      { name: 'tomato', quantity: 120, unit: 'g' },
      { name: 'peas', quantity: 80, unit: 'g' },
      { name: 'potato', quantity: 150, unit: 'g' },
      { name: 'greenchilli', quantity: 20, unit: 'g' },
    ],
    tags: ['vegetarian', 'family-meal'],
  },
  {
    id: 'methi-aloo',
    name: 'Methi Aloo',
    cuisine: 'North Indian',
    mealType: 'Dinner',
    prepTimeMin: 10,
    cookTimeMin: 20,
    ingredients: [
      { name: 'potato', quantity: 200, unit: 'g' },
      { name: 'spinach', quantity: 150, unit: 'g' },
      { name: 'onion', quantity: 60, unit: 'g' },
      { name: 'garlic', quantity: 10, unit: 'g' },
      { name: 'coriander', quantity: 15, unit: 'g' },
    ],
    tags: ['vegetarian', 'budget-friendly'],
  },
  {
    id: 'dal-chaawal',
    name: 'Dal Chawal',
    cuisine: 'Indian',
    mealType: 'Lunch',
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: [
      { name: 'lentil', quantity: 200, unit: 'g' },
      { name: 'rice', quantity: 250, unit: 'g' },
      { name: 'tomato', quantity: 100, unit: 'g' },
      { name: 'onion', quantity: 60, unit: 'g' },
      { name: 'ginger', quantity: 10, unit: 'g' },
    ],
    tags: ['vegetarian', 'comfort-food'],
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    cuisine: 'North Indian',
    mealType: 'Dinner',
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: [
      { name: 'paneer', quantity: 200, unit: 'g' },
      { name: 'tomato', quantity: 200, unit: 'g' },
      { name: 'onion', quantity: 100, unit: 'g' },
      { name: 'garlic', quantity: 20, unit: 'g' },
      { name: 'ghee', quantity: 20, unit: 'ml' },
    ],
    tags: ['vegetarian', 'rich'],
  },
  {
    id: 'curd-rice',
    name: 'Curd Rice',
    cuisine: 'South Indian',
    mealType: 'Lunch',
    prepTimeMin: 10,
    cookTimeMin: 20,
    ingredients: [
      { name: 'rice', quantity: 200, unit: 'g' },
      { name: 'curd', quantity: 150, unit: 'g' },
      { name: 'greenchilli', quantity: 5, unit: 'pcs' },
      { name: 'ginger', quantity: 10, unit: 'g' },
      { name: 'cilantro', quantity: 10, unit: 'g' },
    ],
    tags: ['vegetarian', 'cooling'],
  },
  {
    id: 'egg-bhurji',
    name: 'Egg Bhurji',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    prepTimeMin: 10,
    cookTimeMin: 12,
    ingredients: [
      { name: 'egg', quantity: 4, unit: 'pcs' },
      { name: 'onion', quantity: 50, unit: 'g' },
      { name: 'tomato', quantity: 60, unit: 'g' },
      { name: 'greenchilli', quantity: 10, unit: 'g' },
    ],
    tags: ['high-protein', 'quick'],
  },
];
